version: '3'
services:
  db:
    image: mysql:5.6 
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: websystique

  jenkins:
    image: 'jenkins/jenkins:lts'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - 'jenkins'                                 

  sonar:
    image: ''
    ports:
 nexus:
   image: ''
   ports:


 tomcat:
 #        links:
 #     - db
 #   image: wordpress
 #   volumes:
 #     - wp_data:/var/www/html
 #   ports:
 #     - "8000:80"
 #   environment:
 #     WORDPRESS_DB_HOST: db:3306
 #     WORDPRESS_DB_USER: wordpress
 #     WORDPRESS_DB_PASSWORD: wordpress

volumes:
   mysql:
   jenkins:

