version: '2'
services:
  db:
    image: mysql:5.6 
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Lync123*
      MYSQL_DATABASE: websystique

  jenkins:
    image: 'jenkins/jenkins:lts'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - 'jenkins'                                 

  sonarqube:
    image: 'sonarqube:lts'
    ports: 
      - '9000:9000'

  nexus:
    image: 'sonatype/nexus:oss'
    ports: 
      -  '8081:8081'
    volumes:
      - 'nexus'

  maven-slave:
    image: 'vish4me/maven-slave-image'
    
  web:
    image: tomcat:7.0.96
    # Environment variables do not appear to be getting loaded the first time Tomcat starts!
    #environment:
      #JDBC_URL: jdbc:mysql://db:3306/example_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      #JDBC_USER: root
      #JDBC_PASS: Lync123*
    ports:
      - "8888:8080"
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - tomcat
    #links:
      #- db

volumes:
   mysql:
   jenkins:
   nexus:
   tomcat:

