version: '3'
services:
  db:
    image: mysql:5.6 
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

 # wordpress:
 #   links:
 #     - db
 #   image: wordpress
 #   volumes:
 #     - wp_data:/var/www/html
 #   ports:
 #     - "8000:80"
 #   environment:
 #     WORDPRESS_DB_HOST: db:3306
 #     WORDPRESS_DB_USER: wordpress
 #     WORDPRESS_DB_PASSWORD: wordpress
volumes:
   db_data:
  # wp_data:

